name: Release

on: 
  workflow_dispatch: 

jobs:
  build_and_release:
    permissions:
      contents: read
      pages: write
      id-token: write
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}